### ISSUE TITLE
Being able to do different actions on click

### ISSUE THREAD

**Issue by JurajKubelka** [pharo-ide/Calypso#191]
Hi!

I have implemented a command that shows gt-examples of a particular package and I made it available in the toolbar as I find it convenient (instead of going to a package menu):
![captura de pantalla 2018-02-16 a la s 18 34 43](https://user-images.githubusercontent.com/465505/36330733-a36df5c6-1349-11e8-8c0b-0c37831fae3e.png)

Sometime, I would like to scope the gt-examples for a selected class. And I would like to use the same `Examples` button. For example, with `shift+click` I could scope it for selected classes (instead of packages). Is it possible? How?

Thanks!

**Comment by dionisiydk** [comment]
How you show examples? In the method browser? Did you implement query for them?

I think you can just use Sensor shiftPressed in command preparation method.

**Comment by JurajKubelka** [comment]
I have implemented a plugin and I add a property. I will appreciate if you check the source code, because I am not aware of any query. It is available here:

```
Metacello new
   baseline: 'GToolkitExamples';
   repository: 'github://feenkcom/gtoolkit-examples/src';
   load: 'CalypsoExtensions'
```

**Comment by JurajKubelka** [comment]
The `Sensor shiftPressed` works well. The disadvantage is that only I will know about this feature as it is not visible to user.

**Comment by dionisiydk** [comment]
Ok, I see. You just open inspector.

Maybe you can just check what is actually selected in the browser:
- If class is selected then you will show examples of the class
- if only package is selected then you will show all examples in this package

And it will not forbid to have explicit package menu item which will open all examples independently from selected class

**Comment by dionisiydk** [comment]
Script for loading is not working. (it tells that group is not exists)

**Comment by JurajKubelka** [comment]
I fixed it recently. It should work now. 

I think the issue is in using properties `GtExampleProperty`. I store here relevant Gt-Examples, but this is not updated if a new method (with `gtExample` pragma) is added or removed. What is the correct way to do this? Currently, I ignore it in commands and I compute it again.

**Comment by dionisiydk** [comment]
I looked into the code.

First I think it is bad idea to collect all example methods for every package. It requires full methods scan in all visual packages. So to open browser Calypso will scan all methods in ~20 packages. It can be very slow. Imaging that you browse Object or Morph.
(In case of tests it is not a problem because we are analysing classes without methods).
 
I understand the feature which you want. But to do it carefully we need some clever background processing logic with caching. 
But for decorating classes it is easy.

Also for performance and memory reason it is better to only mark objects that they provide examples.
Commands will collect them when needed.
So try convert ClyExampleProperty to subclass of ClySimpleTag to have  ClyExampleTag.
Then you can mark items using "item markWith: ClyExampleTag". And check items using "item isMarkedWith: ClyExampleTag".

To implement examples method group you need implement subclass of ClyMethodQuery (ClyExampleMethods) and new group provider (ClyExampleMethodGroupProvider). For example look how ClyActiveBreakpoints and ClyBreakMethodGroupProvider are implemented

**Comment by dionisiydk** [comment]
Also look at class ClySampleInstanceScript. 
To decorate gtexample methods you can just copy this class with little changes (you will see).

**Comment by dionisiydk** [comment]
BTW, as soon as you will implement ClyGTExampleMethods query you will be able browse all gtexamples in the system:
```Smalltalk
ClyQueryBrowser openOn: ClyGTExampleMethods new
```

**Comment by dionisiydk** [comment]
And I think a bit more:

1) You decorate classes with icon to open/run examples. I think it is not a good idea because it hides meaningful icon of the class. Look at the Collection classes for example.
Imagine that we will follow gtexamples in general as dev approach. In that case most of the classes in system will provide examples. So all of them will be with same icon. I think it not makes sense.  

So I would only add special method group with icon to open inspector. 
And icons for methods and context menu items. 

2) Conditional menu items for classes and packages not looks useful when system really use examples for all classes. And I think gt users are really use them in so "heavy" way. 
So conditional logic will always affect the browser performance. And maybe it is better to avoid it.

3) Chosen icon do not reflect the purpose. It looks like test icon but it always green which is wrong. Icon updated correctly only in inspector runner.
So I would use same icon as for #sampleInstance methods (classic play button)

**Comment by JurajKubelka** [comment]
Thank you for the detailed review! And please keep the issue open. I will come back to do the proposed changes.
