### ISSUE TITLE
Displaying actually applied methods from traits

### ISSUE THREAD

**Issue by JanBliznicenko** [pharo-ide/Calypso#304]
There is a problem with Calypso displaying all methods of all (recursively) used traits in list of methods, even if those methods are not actually used. There are two cases causing that.

First case is when there are nested traits (trait that uses another trait) and one trait rewrites method from its "inner" trait. In Nautilus, there is only the topmost (actually used) method shown, but in Calypso there are listed all "versions" of the method (version from all traits) and it is very hard to see which one is actually used and which is not. 
I can look how the trait hierarchy looks (which is great!), but I do not want to see all versions of the same method even if only one is actually used - I want to see just the used one.

![2018-07-31 3](https://user-images.githubusercontent.com/9571633/43509786-dfff82d2-9573-11e8-90f7-c85fbabdf6cf.png)

Second case is that Calypso seems to ignore "subtracting" methods from used traits, where in
`uses: TMyTopTrait - {#foo}` the foo method is still in list of methods anyway and aliasing, where in `uses: TMyTopTrait @ {#bar->#foo}` bar does not show anywhere at all although method is actually created

**Comment by dionisiydk** [comment]
Calypso confess different philosophy for traits than Nautilus. It does not
mean that it can't support Nautilus style but it was never be a goal.

For Calypso traits are just a special kind of multiple inheritance. Calypso
does not differ traits and superclasses. They all are inherited objects but
they based on different inheritance mechanizm.
And there is general tool to enable method visibility of those inheritance
objects in the browser.

Trait methods are visible for selected class because there is a setting to
activate *all *traits visibility by default (notice checkbox with green T
icon over first item in protocol panel).
The setting is active by default to mimic Nautilus style but as you see it
is not completely same.

When in traits hierarchy there are many overrides the browser shows all of
them because all inherited trait classes are visible.
It works exactly same way like for many overrides in superclass chain. When
you activate full hierarchy visibility (another checkbox) you will also see
all overridden methods.
Trait and superclass methods here are shown in exactly same logic. In case
of many superclass methods you also need to guess what method is active for
selected class.

To support real Nautilus logic one needs to extend model with new kind of
class scope, something like RawClassScope. It will see all methods which
are really installed into the class. Existing class scopes are implemented
in terms of localMethods (defined methods). Then it will probably require
other changes in the model to be composable with instance side scope, class
side scope and so on.

2018-08-01 9:20 GMT+01:00 Jan Blizničenko <notifications@github.com>:

> There is a problem with Calypso displaying all methods of all
> (recursively) used traits in list of methods, even if those methods are not
> actually used. There are two major cases causing that.
> First case is when there are nested traits (trait that uses another trait)
> and one trait rewrites method from its "inner" trait. In Nautilus, there is
> only the topmost (actually used) method shown, but in Calypso there are
> listed all "versions" of the method (version from all traits) and it is
> very hard to see which one is actually used and which is not.
> I can look how the trait hierarchy looks (which is great!), but I do not
> want to see all versions of the same method even if only one is actually
> used - I want to see just the used one.
>
>
> Second case is that Calypso seems to ignore "subtracting" methods from
> used traits, like
> uses: TMyTopTrait - {#foo} (it displays foo in list of methods anyway).
>
But this just needs to be supported

**Comment by estebanlm** [comment]
nevertheless it still needs to be modified because **it is not multiple inheritance**, is composition and when you override one method you in practice are removing the method the trait provides and replacing it by another.
Proof of that is that if you still want to access to the trait method, you need to alias is (rename it).

**Comment by dionisiydk** [comment]
It's not about modification but implementing new feature. It could become
default in the browser.

But let's not continue repeat our disput. You know my point here. For me
what you describe as a proof is just a technical detail of traits
mechanics. It does not contradict with my idea that traits are just a
special kind of inheritence

чт, 20 сент. 2018 г., 9:08 Esteban Lorenzano <notifications@github.com>:

**Comment by estebanlm** [comment]
no because you cannot do "super myMethod" so is not accessible. 
list it when **is not there** is just confusing.

Anyway, as you said, we already discussed this and my requirement remains so I will work on it :)

**Comment by dionisiydk** [comment]
I have the idea how to implement it.
But now I am busy for details.
In short: inherited scopes should have flag showOverriddenMethods and
return InheritedClass instances instead of real classes

чт, 20 сент. 2018 г., 9:32 Esteban Lorenzano <notifications@github.com>:

**Comment by bliznjan** [comment]
Thank you for looking into that. This is actually only thing keeping me from using Pharo 7 :)
Also I noticed that even aliased methods do not show at all (if you do `uses: TMyTopTrait @ {#bar->#foo}`, bar does not show although method is actually created)

**Comment by dionisiydk** [comment]
I found possible solution. Idea to implement new scope ClyIncreasedClassScope which will take into account overridden method visibility.
It's not yet finished but implementation is not complex and will generally improve some logic around method visibility in browser.
