### ISSUE TITLE
Exporting as PNG right after opening a browser will not display text beyond

### ISSUE THREAD

**Issue by QDucasse** [pharo-ide/Calypso#306]
My goal was to make a screenshot tool which given package/class/method names would export a PNG picture of a System Browser opened given the three previous names and displaying the selected method definition. However, using:
`browser := ClyFullBrowser openOnMethod: Integer>>#isPowerOfTwo.`
`browser exportAsPNGSilently.`
will result in obtaining the following picture:
![a clyfullbrowser 375403264 2018-08-01t14-35-34-840989 02-00](https://user-images.githubusercontent.com/32014573/43522142-b143dffe-9598-11e8-9c5e-a00bb50df263.png)

Adding a delay will not fix the problem, however, executing all lines BUT last THEN last line will result in the correct picture:
![a clyfullbrowser 149058304 2018-08-01t14-41-22-80977 02-00](https://user-images.githubusercontent.com/32014573/43522220-fac69018-9598-11e8-8251-0ea57b6eff35.png)

**Comment by dionisiydk** [comment]
Hi Quentin.

Problem is how tab manager is working. It uses UI stepping mechanizm for
updating tabs while they are built in background. It means that making
pause in your script will prevent updating because script itself is running
in UI process.
So you need to perform waiting in separate process like this:
```Smalltalk
b := ClyFullBrowser openOnMethod: Integer >> #isPowerOfTwo.
[1 seconds wait.
b exportAsPNGSilently] fork
```
It should be possible to avoid static pause with proper synchronization
logic. But it could be tricky.

2018-08-01 13:41 GMT+01:00 Quentin Ducasse <notifications@github.com>:

**Comment by QDucasse** [comment]
Thank you! That explains why

**Comment by dionisiydk** [comment]
So I close it
