### ISSUE TITLE
refactor SystemPlugins* packages

### ISSUE THREAD

**Issue by estebanlm** [pharo-ide/Calypso#320]
Right now, each plugin has 3 packages: 

- browser
- queries
- queries-tests

and that does not has much sense.
I propose to put browser and queries together (we will later see what we do with the tests)

**Comment by dionisiydk** [comment]
I described it on mailing list:

The goal is to separate UI part of plugin from model part. So you can setup server without UI but with required plugins. And you will be able to browse server remotely with all extended features.

The model part of plugin uses Query suffix for package because it extends Calypso queries:
- it extends properties of items which queries return
- it provides new queries
- it introduces new objects which queries can return (new method groups for example)

The UI part of plugin uses Browser suffix for package because it extends browser UI:
- it provides new commands, tabs, table decorations
Browser part can use query part.

I did not choose suffixes Model and UI because it looks like model part of plugin is a model for UI part of plugin. But it is not true

**Comment by estebanlm** [comment]
I understand. Then can't we pack plugins together?

**Comment by dionisiydk** [comment]
I am not sure. Idea was to be modular. 
If system does not have traits you can have browser without traits dependency (no *SystemPlugins-Traits*). If system has no SUnit you can have browser without SUnit dependency (no *SystemPlugins-SUnit*). And so on.

But I also split plugins by features. So probably some of them can be merged. If two plugins have same dependency they can be joined. 

In simplest cases plugins can be moved to Calypso itself like Calypso-SystemPlugins-MethodDiffTool.

**Comment by estebanlm** [comment]
yes, we can work on this. 
but well, later :)
