### ISSUE TITLE
Do not display class/instance together on extension list

### ISSUE THREAD

**Issue by estebanlm** [pharo-ide/Calypso#335]
When selecting a package that has extension methods defined, the displayed including class extensions regardless the visibility selection (class or instance), creating a confusing view where both instance sides and classes coexist.

Thing is, this feature does not works. It just confuses people so "old" behaviour is better there,

**Comment by dionisiydk** [comment]
A bit of my story:
When I first time implemented extended classes in class pane I also thought that it was a bug to shows "AClass class" or even together "AClass class" and "AClass". There were many other tasks. So I lived with this a long time.
But then I noticed how it is actually useful because it is super simple way to see what exactly is extended by package, what exact side of a class is extended. In Nautilus I every time was interrupted when I did not find extension methods after selecting extended class (grey class) because they were defined on opposite class side. It always forced me to think where are methods and what to do to show them.
Then I added automatic selection of extension protocol for extended classes and browsing extensions started to be even better. (click on extended class shows extensions instead of all methods and switches browser to the right side of class).

So that is my vision. I understand that others could not share it. We can do it configurable.

To better feel my point try to browse all extensions of some package in Calypso and Nautilus. In Calypso it would be simple "arrow down/up" over extended classes. In Nautilus you will also need to switch class side time to time.

**Comment by dionisiydk** [comment]
> Thing is, this feature does not works. 

This part I don't understand because scenario which I describe is working fine. So what is the feature?

**Comment by estebanlm** [comment]
It does not works because it does now matches the proposed cognitive model: you have two sides class/instance. Class side methods goes in class side and instance side methods goes in instance side. 
It is already hard to explain to newcomers this distinction (which I know we need to improve, but that's another discussion). Browser is designed to show one side hierarchy. 
And now you come and say: there is class side and instance side. Except when there is an extensión. In that case, there is no distinction. But you will get a list of class A and class A class. 
 
And **that** does not works. Because It is not coherent. 

Now, I do not mind if there is an option so you can put it there for you case (because you can have divergent mental models living together without trouble). But the **general** case needs to be as I say :)
