### ISSUE TITLE
Adding a Trait to a class and saving do not update the methods

### ISSUE THREAD

**Issue by jecisc** [pharo-ide/Calypso#361]
I added a trait to an existing class and saved but to see the methods of the class I had to change of selected class and come back. 

Saving a class should refresh the methods.

**Comment by dionisiydk** [comment]
It is fixed (not exist) in dev version due to removed trait inheritance
logic (methods instead of localMethods).

By the way there is non trait scenario. Try enable visibility of superclass
methods and then replace superclass to Object in class definition. The
method pane will still show original superclass methods but they not exist
in hierarchy anymore. I opened for #363 for this

пн, 12 нояб. 2018 г. в 13:17, CyrilFerlicot <notifications@github.com>:

**Comment by dionisiydk** [comment]
Fixed and integrated
